# Generated by Django 3.2.3 on 2021-05-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seeds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_name', models.CharField(max_length=50)),
                ('seed_variety', models.CharField(max_length=50)),
                ('seed_type', models.CharField(max_length=50)),
                ('seed_planting_zone', models.CharField(max_length=4)),
                ('germination_period', models.CharField(max_length=4)),
                ('days_to_harvest', models.CharField(max_length=4)),
                ('plant_spacing', models.CharField(max_length=4)),
                ('row_spacing', models.CharField(max_length=4)),
                ('plant_depth', models.CharField(max_length=4)),
                ('sun_requirements', models.CharField(max_length=4)),
                ('water_requirements', models.CharField(max_length=4)),
            ],
        ),
    ]
